### ISSUE TITLE
Distributed WebSocket Server

### ISSUE THREAD

**Issue by lvl-mattwells** [lvl-mattwells/DevsPlayingPoker#86] opened 2023-01-18 15:30 UTC
What if we could separate the WebSocket aspect of the BE to its own service and have it run independently from the HTTP server? Then, when a new room is created, we start an instance of the WebSocket piece on a server close to the moderator (via the Edge). Then anyone who connects to that room connects to that server. That could help with distribution/performance. The most important piece is making sure a room is tied to a server. Otherwise not everyone in the room's socket connection will live on the same server and not get updates.

I have no idea how to do this, but how freaking cool would that be.

**Comment by lvl-mattwells** [comment] 2023-01-18 15:56
We could also just simply separate the file server from the websocket server and run them on two different servers. Maybe have the website part run in Deno Deploy at the edge and then run only the WebSocket server in Fly.io

**Comment by lvl-mattwells** [comment] 2023-01-18 18:19
Or we could turn the web part into a SolidStart app and deploy it on Vercel and still host the WS server on Fly.io

**Comment by mattwells19** [comment] 2023-03-25 22:56
Duplicate of [Feature: Bun + SolidStart](https://github.com/lvl-mattwells/DevsPlayingPoker/milestone/2)

**Closed by mattwells19** 2023-03-25 22:56 UTC
Labels: Feature
